# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.auto", false);
user_pref("app.update.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1401465086);
user_pref("app.update.lastUpdateTime.background-update-timer", 1401464966);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1401465206);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1402493635);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1402493755);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.cache.frecency_experiment", 4);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 22);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.preferences.advanced.selectedTabIndex", 3);
user_pref("browser.rights.3.shown", true);
user_pref("browser.sessionhistory.max_total_viewers", 0);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20141113143407");
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.slowStartup.averageTime", 1141);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20141113143407");
user_pref("browser.startup.homepage_override.mstone", "33.1.1");
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.uitour.whitelist.add.260", "");
user_pref("browser.uitour.whitelist.add.340", "");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1396742374165");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1402493577674");
user_pref("datareporting.policy.firstRunTime", "1396655974165");
user_pref("datareporting.sessions.current.activeTicks", 11);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 1023);
user_pref("datareporting.sessions.current.main", 62);
user_pref("datareporting.sessions.current.sessionRestored", 1172);
user_pref("datareporting.sessions.current.startTime", "1416267807364");
user_pref("datareporting.sessions.current.totalTime", 51);
user_pref("datareporting.sessions.currentIndex", 11);
user_pref("datareporting.sessions.previous.10", "{\"s\":1406317022240,\"a\":7,\"t\":49,\"c\":true,\"m\":62,\"fp\":1024,\"sr\":1118}");
user_pref("datareporting.sessions.previous.5", "{\"s\":1401221375336,\"a\":3,\"t\":14,\"c\":true,\"m\":63,\"fp\":2334,\"sr\":3163}");
user_pref("datareporting.sessions.previous.6", "{\"s\":1401464600280,\"a\":31,\"t\":5662,\"c\":true,\"m\":3828,\"fp\":7410,\"sr\":7518}");
user_pref("datareporting.sessions.previous.7", "{\"s\":1402493511584,\"a\":7,\"t\":280,\"c\":true,\"m\":2484,\"fp\":4354,\"sr\":4464}");
user_pref("datareporting.sessions.previous.8", "{\"s\":1402609059182,\"a\":6,\"t\":47,\"c\":true,\"m\":63,\"fp\":888,\"sr\":989}");
user_pref("datareporting.sessions.previous.9", "{\"s\":1403277577924,\"a\":4,\"t\":20,\"c\":true,\"m\":1152,\"fp\":3023,\"sr\":3107}");
user_pref("datareporting.sessions.prunedIndex", 4);
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:33.1.1");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20140319.01");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"C:\\\\Program Files\\\\Mozilla Firefox\\\\browser\\\\extensions\\\\{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1416267489710,\"rdfTime\":1416267489428}}}]");
user_pref("extensions.lastAppVersion", "33.1.1");
user_pref("extensions.lastPlatformVersion", "33.1.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("gecko.buildID", "20141113143407");
user_pref("gecko.mstone", "33.1.1");
user_pref("idle.lastDailyNotification", 1401464800);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("places.database.lastMaintenance", 1401464800);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1400675175);
user_pref("toolkit.startup.last_success", 1416267807);
user_pref("toolkit.telemetry.previousBuildID", "20141113143407");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1399247977);
